# Customs Office configuration file

# Citizens NPC ID (not UUID) that when clicked, opens the Customs Office gui
npc-id: -1
# Time in seconds when the non-native animals spawn in their respective world guard regions
# Default is set to 5 days
time-between-event: 432000

# Time in unix format when the non-native animal event occurs
# This number automatically updates according to the time-between-restock value and the last event
# Do not touch unless you know what you are doing
animal-event-time: 0
